PREFIX gr: <http://purl.org/goodrelations/v1#>

# test query
## test query no. 1
CONSTRUCT {
    ?s gr:ean ?ean;
        gr:name bif:concat(?ean,?test) .
    FILTER(bif:contains(?sparwl, "test123"))
}
WHERE {
    ?s a gr:Offering;
        gr:hasEAN_UCC-13 ?ean;
        gr:description "ACME"@en .
    FILTER(!bound(?s))
}
