PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX foo: <#>

SELECT ?name
WHERE {
  ?offer a gr:Offering;
    gr:name ?name;
    gr:hasPriceSpecification [
        a gr:UnitPriceSpecification;
        gr:hasCurrency "EUR";
        gr:hasCurrencyValue 10.00; # test numeric literals
        gr:hasUnitOfMeasurement "C62"
    ];
    gr:includes foo:product1 .
}
